/**
 * Language info
 */
  
/* Strings */
const language_list = {

    "en" : {
        "welcome"       : "Welcome",
        "welcome_text"  : "Welcome to The Flying Dutchman",
        "login"         : "Login",
        "register"      : "Register",
        "logout"        : "Logout",
        "username"      : "username",
        "name"          : "name",
        "surname"       : "surname",
        "email"         : "email",
        "password"      : "password",
        "home"          : "Home",
        "menu"          : "Menu",
        "favourites"    : "Favourites",
        "tray"          : "Tray",
        "beer"          : "Beer",
        "ale"           : "Ale",
        "stout"         : "Stout",
        "lager"         : "Lager",
        "cider"         : "Cider",
        "spirit"        : "Spirit",
        "whisky"        : "Whisky",
        "wine"          : "Wine",
        "red_wine"      : "Red Wine",
        "white_wine"    : "White Wine",
        "rose_wine"     : "Rosé Wine",
        "checkout"      : "Checkout",
        "amount"        : "Amount:",
        "option_card"   : "Credit / Debit Card",
        "option_credit" : "Flying Dutchman Credit",
        "cardholder"    : "Cardholder's Name",
        "cardnumber"    : "Card Number",
        "expiry_date"   : "Expiry Date (MM/YY)",
        "cvc"           : "CVV/CVC",
        "back"          : "Back",
        "confirm_pay"   : "Confirm Payment",
        "your_credit"   : "Your credit:",
        "your_tray"     : "Your Tray",
        "pay"           : "Pay",
        "reset"         : "Reset",
        "confirm_order" : "Confirm order",
        "yes"           : "Yes",
        "no"            : "No",
    },  

    "sv" : {
        "welcome"       : "Välkommen",
        "welcome_text"  : "Välkommen till The Flying Dutchman",
        "login"         : "Logga in",
        "register"      : "Registrera",
        "logout"        : "Logga ut",
        "username"      : "användarnamn",
        "name"          : "namn",
        "surname"       : "efternamn",
        "email"         : "e-post",
        "password"      : "lösenord",
        "home"          : "Hem",
        "menu"          : "Meny",
        "favourites"    : "Favoriter",
        "tray"          : "Bricka",
        "beer"          : "Öl",
        "ale"           : "Ale",
        "stout"         : "Stout",
        "lager"         : "Lageröl",
        "cider"         : "Cider",
        "spirit"        : "Spritdryck",
        "whisky"        : "Whisky",
        "wine"          : "Vin",
        "red_wine"      : "Rödvin",
        "white_wine"    : "Vitt Vin",
        "rose_wine"     : "Rosévin",
        "checkout"      : "Kassa",
        "amount"        : "Belopp:",
        "option_card"   : "Kreditkort / Betalkort",
        "option_credit" : "Flying Dutchman Kredit",
        "cardholder"    : "Kortinnehavarens Namn",
        "cardnumber"    : "Kortnummer",
        "expiry_date"   : "Utgångsdatum (MM/YY)",
        "cvc"           : "CVV/CVC",
        "back"          : "Tillbaka",
        "confirm_pay"   : "Bekräfta Betalning",
        "your_credit"   : "Din kredit:",
        "your_tray"     : "Din Bricka",
        "pay"           : "Betala",
        "reset"         : "Återställa",
        "confirm_order" : "Bekräfta order",
        "yes"           : "Ja",
        "no"            : "Nej",
    }
};