/**
 * Language info
 */
  
/* Strings */
const language_list = {

    "en" : {
        "welcome"       : "Welcome",
        "welcome_text"  : "Welcome to The Flying Dutchman",
        "login"         : "Login",
        "register"      : "Register",
        "username"      : "username",
        "email"         : "email",
        "password"      : "password",
        "home"          : "Home",
        "menu"          : "Menu",
        "favourites"    : "Favourites",
        "tray"          : "Tray",
        "beer"          : "Beer",
        "cider"         : "Cider",
        "spirit"        : "Spirit",
        "wine"          : "Wine",
        "checkout"      : "Checkout",
        "amount"        : "Amount:",
        "option_card"   : "Credit / Debit Card",
        "option_credit" : "Flying Dutchman Credit",
        "cardholder"    : "Cardholder's Name",
        "cardnumber"    : "Card Number",
        "expiry_date"   : "Expiry Date (MM/YY)",
        "cvc"           : "CVV/CVC",
        "back"          : "Back",
        "confirm_pay"   : "Confirm Payment",
        "your_credit"   : "Your credit:",
        "your_tray"     : "Your Tray",
    },  

    "sv" : {
        "welcome"       : "Välkommen",
        "welcome_text"  : "Välkommen till The Flying Dutchman",
        "login"         : "Logga in",
        "register"      : "Registrera",
        "username"      : "användarnamn",
        "email"         : "e-post",
        "password"      : "lösenord",
        "home"          : "Hem",
        "menu"          : "Meny",
        "favourites"    : "Favoriter",
        "tray"          : "Bricka",
        "beer"          : "Öl",
        "cider"         : "Cider",
        "spirit"        : "Spritdryck",
        "wine"          : "Vin",
        "checkout"      : "Kassa",
        "amount"        : "Belopp:",
        "option_card"   : "Kreditkort / Betalkort",
        "option_credit" : "Flying Dutchman Kredit",
        "cardholder"    : "Kortinnehavarens Namn",
        "cardnumber"    : "Kortnummer",
        "expiry_date"   : "Utgångsdatum (MM/YY)",
        "cvc"           : "CVV/CVC",
        "back"          : "Tillbaka",
        "confirm_pay"   : "Bekräfta Betalning",
        "your_credit"   : "Din kredit:",
        "your_tray"     : "Din Bricka",
    }
};